### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by Strijd** [mathewmeconry/icinga2-aws#4]
Hi
Can you please give an example for icinga2 ?
Supports auto scaling?
thanks

**Comment by mathewmeconry** [comment]
Hi
sure. I'll add one to the readme in the next few days
yes it supports auto scaling. that was the reason why I created this script

**Comment by mathewmeconry** [comment]
Hi @Strijd 
As you can see I added an example with the commit bcb5ad6.
Please check if this helps you
