### ISSUE TITLE
unable to relaod icinga after importing, getting syntax error.

### ISSUE THREAD

**Issue by chiju** [mathewmeconry/icinga2-aws#5]
Hi Mathew,

I executed the script and can see that the hosts are created inside the conf but not able to reload  icinga service, getting below error while reloading 

getting below error while reloading icinga2: systemctl status icinga2.service -l

Error
===
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: [2019-07-12 08:24:34 +0000] information/cli: Loading configuration file(s).
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: [2019-07-12 08:24:34 +0000] critical/config: Error: syntax error, unexpected T_IDENTIFIER, expecting '{'
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: Location: in /etc/icinga2/conf.d/hosts/i-037eaab2849ca7221/i-037eaab2849ca7221.conf: 2:18-2:31
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: /etc/icinga2/conf.d/hosts/i-037eaab2849ca7221/i-037eaab2849ca7221.conf(1): /* i-037eaab2849ca7221 gets replaced with the InstanceID */
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: /etc/icinga2/conf.d/hosts/i-037eaab2849ca7221/i-037eaab2849ca7221.conf(2): object Host i-037eaab2849ca7221 {
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: ^^^^^^^^^^^^^^
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: /etc/icinga2/conf.d/hosts/i-037eaab2849ca7221/i-037eaab2849ca7221.conf(3):   import "generic-host"
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal safe-reload[17349]: /etc/icinga2/conf.d/hosts/i-037eaab2849ca7221/i-037eaab2849ca7221.conf(4):
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal systemd[1]: icinga2.service: control process exited, code=exited status=1
Jul 12 08:24:34 ip-x.x.x.x.ap-x-1.compute.internal systemd[1]: Reload failed for Icinga host/service/network monitoring system.

why this is happing, could you please help

Execution
=====
python3 ./icinga2-aws.py -t Name:centos-icinga_director -th example/hostconfig.conf.example -tc example/checkconfig.conf.example

Environment
=====
aws ec2 instance
centos 7
icinga2
php 7

**Comment by mathewmeconry** [comment]
Hi @chiju 

could you please send me the file i-037eaab2849ca7221.conf to have more information?

**Comment by chiju** [comment]
Hi @mathewmeconry ,

Thanks for responding, I was able to resolve it by adding "double quotes" for "{HOST}" after object Host manually after executing the script, but I am doing this using ansible. 

object Host {HOST} {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "{PublicIP} "
  address6 = "::1"

**Comment by mathewmeconry** [comment]
This is probably a typo in the example. Try to add the "double quotes" for the {HOST} in the template.
This should do the trick.

If it works please tell that I can change the template. I don't have any environment to test at this moment

**Comment by chiju** [comment]
It is working after adding the "double quotes" for the {HOST} in the template.

**Comment by chiju** [comment]
Hi Mathew,

without check config I am not able to excute the script, i mean the "-tc" option 

[root@ip-x-x-xx- icinga2-aws-master]# python3 icinga2-aws.py -t Name:centos-icinga_director -th /root/icinga2-aws-master/hosts.conf 
Traceback (most recent call last):
  File "icinga2-aws.py", line 119, in <module>
    templateCheck = args.templateCheck.read()
AttributeError: 'NoneType' object has no attribute 'read'

can it be optional?

**Comment by mathewmeconry** [comment]
From my point of view the config has to be mandatory because the host.conf and checks.conf should be in separated files
